news:
  image: stockflare/api-news-posts-stub
  command: puma
  environment: 
    PORT: 22345
  ports:
    - "22345:22345"


stockflare:
  build: .
  command: rails server -p 4444
  environment:
    PORT: 4444
  ports:
    - "4444:4444"
  volumes:
    - .:/stockflare
  links:
    - news