database:
  image: tutum/mysql
  ports:
    - "3306"
  environment:
    MYSQL_USER: root
    MYSQL_PASS: password
news:
  build: .
  command: bundle exec dotenv puma
  environment:
    PORT: 2345
    SERVICE_POSTS_NEWS_URL: posts.news.internal-stocktio.com
  ports:
    - "2345:2345"
  volumes:
    - .:/stockflare
  links:
    - database
