database:
  image: tutum/mysql
  ports:
    - "3306"
  environment:
    MYSQL_USER: root
    MYSQL_PASS: password
news:
  image: stockflare/api-news-posts-stub
  command: puma
  environment:
    PORT: 4545
  ports:
    - "4545"
stockflare:
  build: .
  command: bundle exec dotenv puma
  environment:
    PORT: 2345
  ports:
    - "2345:2345"
  volumes:
    - .:/stockflare
  links:
    - news
    - database
